<?php
/**
 * Created by JetBrains PhpStorm.
 * User: irina
 * Date: 5/28/13
 * Time: 11:27 AM
 * To change this template use File | Settings | File Templates.
 */

namespace Application\Api\Base\Server;

use Application\Lib\Rpc\JsonRpc\Server\RpcRouter as AbstractRouter;


/**
 * Class RpcRouter
 *
 * @package Application\Api\Base\Server
 */
class RpcRouter
    extends AbstractRouter
{

    /**
     * override just for proper type hinting in ide
     *
     * @return RpcFactory
     */
    public function getFactory()
    {
        return parent::getFactory();
    }

    /**
     * override just for proper type hinting in ide
     *
     * @return Rpc
     */
    public function getRpc()
    {
        return parent::getRpc();
    }

    protected function handleRpc()
    {
        // TODO: Change the autogenerated stub
        return parent::handleRpc();
    }


}